# Staking Ledger Allocations in YAML so we can comment as needed

accounts:
  backers:
    amount: "2300000000"
    address: "oasis1qp29h8ykmxet46eqzw0wennrmmy4al3xzv37m3ca"
    csv_label: "---no label---"

  community_and_ecosystem:
    amount: "2269572950"
    address: "oasis1qrad7s7nqm4gvyzr8yt2rdk0ref489rn3vn400d6"
    csv_label: "Community Delegation"

  core_contributors:
    amount: "2000000000"
    address: "oasis1qqs6ylpfurhf6gc9mw232fkmrt3d0673lyzc5xf2"
    csv_label: "Core Contributor Delegation"

  strategic_partners_and_reserve:
    amount: "500000000"
    address: "oasis1qpdks9ccwxa27hyccd78d58vhpl9wyddmy4xvhvk"
    csv_label: "Strategic Partners & Reserve Delegation"

  foundation_endowment:
    amount: "1000000000"
    address: "oasis1qp7hpak0wuymn3pqtwf2cpaxsm25v6ydhuzkxupe"
    csv_label: "Foundation Ecosystem Delegation [Amber rewards]"

csv_options:
  kyc_label: "KYC Complete"
  entity_package_submitted_label: "Entity Submitted"
  entity_package_name_label: "Entity Package Name"
  funding_label: "Total Rewards [sum of Quest + Grants, paid out from community & ecosystem]"

##
# BELOW ARE FUNDING ALLOCATIONS FOR TEST ONLY GENESIS DOCUMENTS
##
test_only_entities:
  rvg:
    funds: 600000000
  pro-wh:
    funds: 600000000
  peterjgilbert:
    funds: 600000000

# This is the minimum balance that should be left in an account
minimum_balance: 100
token_value_exponent: 9
token_symbol: ROSE
total_supply: 10000000000

commission_rate_max: 20000
commission_rate_min: 0
commission_rate: 5000
