# Staking Ledger Allocations in YAML so we can comment as needed

accounts:
  backers:
    amount: "2300000000"
    address: "oasis1qz2kz3zkgf6trclyajtyg4jecw7es7p5tutfqaz0"
    csv_label: "---no label---"

  community_and_ecosystem:
    amount: "2269572950"
    address: "oasis1qqfjknq5jlelnfd0xtc38u9t25u467nasuzytpe3"
    csv_label: "Community Delegation"

  core_contributors:
    amount: "2000000000"
    address: "oasis1qzpjtg2zhqqun6nmvclrtdmwuxeluj6pxgvedwzu"
    csv_label: "Core Contributor Delegation"

  strategic_partners_and_reserve:
    amount: "500000000"
    address: "oasis1qpn5qckl50vfn0phmn545ufrypvfqqzhwgaprxv5"
    csv_label: "Strategic Partners & Reserve Delegation"

  foundation_endowment:
    amount: "1000000000"
    address: "oasis1qpu9qf32765nl5ql8jkh6zmrlwvu23srecu5phac"
    csv_label: "Foundation Ecosystem Delegation [Amber rewards]"

csv_options:
  kyc_label: "KYC Complete"
  entity_package_submitted_label: "Entity Submitted"
  entity_package_name_label: "Entity Package Name"
  funding_label: "Total Rewards [sum of Quest + Grants, paid out from community & ecosystem]"

##
# BELOW ARE FUNDING ALLOCATIONS FOR TEST ONLY GENESIS DOCUMENTS
##
test_only_entities:
  rvg:
    funds: 600000000
  pro-wh:
    funds: 600000000
  peterjgilbert:
    funds: 600000000

# This is the minimum balance that should be left in an account
minimum_balance: 100
token_value_exponent: 9
token_symbol: ROSE
total_supply: 10000000000

commission_rate_max: 20000
commission_rate_min: 0
commission_rate: 5000
